project:
  type: website

website:
  title: "nionmaron"
  navbar:
    right:
      - Blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/nionmaron/
      - icon: github
        href: https://github.com
        
        

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

